# Generated by Django 5.0.2 on 2024-02-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="pet_pics/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("breed", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
