# Generated by Django 5.0.4 on 2024-04-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="num_friends",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
