# Generated by Django 5.0.4 on 2024-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PetManagement", "0003_alter_pet_owner"),
        ("UserManagement", "0002_customuser_num_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pets",
            field=models.ManyToManyField(
                blank=True, related_name="owners", to="PetManagement.pet"
            ),
        ),
    ]
