import json
import pandas as pd
from django.core.management.base import BaseCommand
from django.conf import settings
from faker import Faker
from pathlib import Path
from UserManagement.serializers import CustomUserSerializer


class Command(BaseCommand):
    help = 'Creates dummy users from an Excel file'

    def handle(self, *args, **kwargs):
        # Define the path to the Excel file
        excel_file_path = Path(settings.BASE_DIR) / 'misc' / 'DummyData.xlsx'

        # Load the Excel file
        df = pd.read_excel(excel_file_path, header=1)

        fake = Faker()
        for _ in range(250):  # Adjust the range as needed
            row = df.sample(n=1).iloc[0]
            user_data = {
                'username': fake.user_name(),
                'email': fake.email(),
                'password': 'TempPass!234',
                'first_name': fake.first_name(),
                'last_name': fake.last_name(),
                'city': row['City'],
                'state': row['State'],
                'zip_code': str(row['Zip']),
                'preferred_language': 'en',
                'display_name': fake.user_name(),
                'has_pets': fake.boolean(),
                'about_me': 'This is an autogenerated user.',
                'new_pets': [
                    {
                        'name': fake.name(),
                        'age': fake.random_int(min=1, max=20),
                        'pet_type': fake.random_element(elements=('dog', 'cat', 'bird', 'reptile', 'other')),
                    }
                    for _ in range(fake.random_int(min=0, max=3))
                ],
            }

            serializer = CustomUserSerializer(data=user_data)
            if serializer.is_valid():
                serializer.save()
                self.stdout.write(self.style.SUCCESS(
                    f"Successfully created user {user_data['first_name']} {user_data['last_name']}."))
            else:
                errors = json.dumps(serializer.errors, indent=4)
                self.stdout.write(self.style.ERROR(
                    f"Failed to create user {user_data['first_name']} {user_data['last_name']}: {errors}"))
